// Generated by Wrangler by running `wrangler types src/worker-configuration.d.ts`

interface Env {
	ENVIRONMENT: string
	DISCORD_TOKEN: string
	SUPABASE_API_URL: string
	SUPABASE_SECRET_KEY: string
}
